# Deutsche A1 Wortschatz – kurze Liste zum Üben

WORDS = [
    {"de": "Hallo", "zh": "你好；喂"},
    {"de": "Guten Morgen", "zh": "早上好"},
    {"de": "Guten Tag", "zh": "日安；你好"},
    {"de": "Guten Abend", "zh": "晚上好"},
    {"de": "Gute Nacht", "zh": "晚安"},
    {"de": "Danke", "zh": "谢谢"},
    {"de": "Bitte", "zh": "请；不客气"},
    {"de": "Entschuldigung", "zh": "对不起；打扰一下"},
    {"de": "Ja", "zh": "是"},
    {"de": "Nein", "zh": "不"},
    {"de": "Ich", "zh": "我"},
    {"de": "du", "zh": "你"},
    {"de": "er / sie / es", "zh": "他 / 她 / 它"},
    {"de": "wir", "zh": "我们"},
    {"de": "ihr", "zh": "你们"},
    {"de": "sie / Sie", "zh": "他们；她们；（尊称）您"},
    {"de": "sein", "zh": "是（动词）"},
    {"de": "haben", "zh": "有"},
    {"de": "gehen", "zh": "去；走"},
    {"de": "kommen", "zh": "来"},
    {"de": "machen", "zh": "做"},
    {"de": "Haus", "zh": "房子；家"},
    {"de": "Wohnung", "zh": "公寓"},
    {"de": "Zimmer", "zh": "房间"},
    {"de": "Tür", "zh": "门"},
    {"de": "Fenster", "zh": "窗"},
    {"de": "Tisch", "zh": "桌子"},
    {"de": "Stuhl", "zh": "椅子"},
    {"de": "Bett", "zh": "床"},
    {"de": "Familie", "zh": "家庭"},
    {"de": "Mutter", "zh": "母亲"},
    {"de": "Vater", "zh": "父亲"},
    {"de": "Bruder", "zh": "兄弟"},
    {"de": "Schwester", "zh": "姐妹"},
    {"de": "Freund / Freundin", "zh": "男性朋友 / 女性朋友"},
    {"de": "Kind", "zh": "孩子"},
    {"de": "Mann", "zh": "男人；丈夫"},
    {"de": "Frau", "zh": "女人；夫人；太太"},
    {"de": "Wasser", "zh": "水"},
    {"de": "Brot", "zh": "面包"},
    {"de": "Milch", "zh": "牛奶"},
    {"de": "Kaffee", "zh": "咖啡"},
    {"de": "Tee", "zh": "茶"},
    {"de": "Apfel", "zh": "苹果"},
    {"de": "Banane", "zh": "香蕉"},
    {"de": "essen", "zh": "吃"},
    {"de": "trinken", "zh": "喝"},
    {"de": "heiß", "zh": "热的"},
    {"de": "kalt", "zh": "冷的"},
    {"de": "groß", "zh": "大的；高的"},
    {"de": "klein", "zh": "小的"},
    {"de": "gut", "zh": "好的"},
    {"de": "schlecht", "zh": "坏的"},
    {"de": "neu", "zh": "新的"},
    {"de": "alt", "zh": "老的；旧的"},
    {"de": "schön", "zh": "美丽的"},
    {"de": "heute", "zh": "今天"},
    {"de": "gestern", "zh": "昨天"},
    {"de": "morgen", "zh": "明天；早晨"},
    {"de": "jetzt", "zh": "现在"},
    {"de": "Montag", "zh": "星期一"},
    {"de": "Dienstag", "zh": "星期二"},
    {"de": "Sommer", "zh": "夏天"},
    {"de": "Winter", "zh": "冬天"},
    {"de": "Stadt", "zh": "城市"},
    {"de": "Land", "zh": "国家；农村"},
    {"de": "Schule", "zh": "学校"},
    {"de": "Arbeit", "zh": "工作"},
    {"de": "Buch", "zh": "书"},
    {"de": "Zeitung", "zh": "报纸"},
    {"de": "lernen", "zh": "学习"},
    {"de": "lesen", "zh": "读"},
    {"de": "schreiben", "zh": "写"},
    {"de": "sprechen", "zh": "说"},
    {"de": "hören", "zh": "听"},
    {"de": "sehen", "zh": "看见"},
    {"de": "verstehen", "zh": "理解"},
    {"de": "fragen", "zh": "问"},
    {"de": "antworten", "zh": "回答"},
    {"de": "können", "zh": "能够"},
    {"de": "müssen", "zh": "必须"},
    {"de": "wollen", "zh": "想要"},
    {"de": "dürfen", "zh": "被允许"},
    {"de": "eins", "zh": "一"},
    {"de": "zwei", "zh": "二"},
    {"de": "zehn", "zh": "十"},
    {"de": "hundert", "zh": "一百"},
]
